### ISSUE TITLE
the app name does not accept an evironment variable

### ISSUE THREAD

**Issue by ludicruz** [heroku/heroku-jenkins-plugin#18]
When trying to build a single jenkins job around running processes I had a variable injected which is the app name. This isn't being translated to the value of the variable. Getting an error tryign to hit https://api.heroku.com/apps/${HEROKU_APP}

**Comment by jkutner** [comment]
This plugin is deprecated, and no longer support. Please see the Heroku guide to [Deploying WAR Files](https://devcenter.heroku.com/articles/war-deployment) instead. And let us know if you have any questions
